name: Bug report
description: Report unexpected behaviour that should be fixed
labels:
  - bug
  - triage
body:
  - type: textarea
    attributes:
      label: Reproduction steps
      description: What did you do to trigger this bug?
      placeholder: |
        1. Go to...
        2. Click on...
        3. Scroll down to...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Resulting behaviour
      description: What happens?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behaviour
      description: What did you expect to happen?
    validations:
      required: true
  - type: input
    attributes:
      label: Logs
      description: Link to logs, if any (you can use a [GitHub gist](https://gists.github.com), it accepts multiple files).
  - type: input
    attributes:
      label: Spock version
      placeholder: e.g. 0.0.1-alpha.4
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Affected modules
      description: The modules this bug affects. If you don't know what this means, feel free to ignore this.
      multiple: true
      options:
        - Build Process
        - Core
        - Documentation
        - Examples
        - Glfw
        - Math
        - Math Codegen
        - Toolkit
        - Utilities
        - Windowing
        - Other
    validations:
      required: true
  - type: input
    attributes:
      label: Kotlin version
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Affected targets
      description: The targets the bug appears at, if relevant.
      multiple: true
      options:
        - Android
        - JVM
        - Native
        - WasmJS
  - type: dropdown
    attributes:
      label: Operating system
      description: Select all operating systems you've encountered this bug on.
      multiple: true
      options:
        - Android
        - Android TV
        - Android Wear OS
        - Apple iOS
        - Apple iPadOS
        - Apple macOS
        - Apple tvOS
        - Apple watchOS
        - ChromeOS
        - ChromeOS Flex
        - FreeBSD
        - Linux
        - Linux via Wine/Proton
        - Windows
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Architecture
      description: Select all architectures you've encountered this bug on.
      multiple: true
      options:
        - x64
        - Arm64
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Windowing protocol
      description: |
        Select all windowing protocols you've encountered this bug on.
        You can ignore this if you aren't using Linux or FreeBSD, or if you don't know what it means.
      multiple: true
      options:
        - Wayland
        - X11
  - type: textarea
    attributes:
      label: Additional context
      description: |
        Operating system version/distro, screenshots, JVM version, Kotlin version, gradle version,
        browser and version, etc.
