name: Bug report
description: Report unexpected behaviour that should be fixed
labels:
  - bug
  - triage
body:
  - type: textarea
    attributes:
      label: Reproduction steps
      description: What did you do to trigger this bug?
      placeholder: |
        1. Go to...
        2. Click on...
        3. Scroll down to...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Resulting behaviour
      description: What happens?
      placeholder: Description, screenshots, exceptions...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behaviour
      description: What did you expect to happen?
    validations:
      required: true
  - type: input
    attributes:
      label: Logs
      description: Link to logs, if any. You can upload to [GitHub gist](https://gist.github.com)—it accepts multiple files.
      placeholder: https://gist.github.com/user/...
  - type: input
    attributes:
      label: Spock version
      placeholder: e.g. 0.0.1-alpha.4
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Affected modules
      description: Select the Spock modules this bug relates to. If you don't know, select other.
      multiple: true
      options:
        - Build process
        - Core
        - Documentation
        - Examples
        - Glfw
        - Math
        - Math Codegen
        - Toolkit
        - Utilities
        - Windowing
        - Other...
    validations:
      required: true
  - type: input
    attributes:
      label: Kotlin version
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Affected targets
      description: Kotlin targets the bug affects. Note Android Native counts as Kotlin/Native, not Kotlin/Android.
      multiple: true
      options:
        - Android
        - JVM
        - Native
        - WasmJS
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Operating system
      description: Select all operating systems you've encountered this bug on.
      multiple: true
      options:
        - Android
        - Android TV
        - Android Wear OS
        - Apple iOS
        - Apple iPadOS
        - Apple macOS
        - Apple tvOS
        - Apple watchOS
        - ChromeOS
        - ChromeOS Flex
        - FreeBSD
        - Linux
        - Linux via Wine/Proton
        - Windows
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Architecture
      description: Select all architectures you've encountered this bug on.
      multiple: true
      options:
        - x64
        - Arm64
    validations:
      required: true
  - type: dropdown
    attributes:
      label: GPU class
      description: Select all categories that fit a GPU you've encountered this bug on, if relevant.
      multiple: true
      options:
        - AMD Dedicated
        - AMD Integrated
        - AMD SoC
        - Apple SoC
        - Intel Dedicated
        - Intel Integrated
        - Qualcomm SoC
  - type: dropdown
    attributes:
      label: Windowing protocol
      description: |
        Select all windowing protocols you've encountered this bug on.
        Feel free to leave this empty if you aren't using Linux or FreeBSD, or if you don't know what it means.
      multiple: true
      options:
        - Wayland
        - X11
  - type: textarea
    attributes:
      label: Additional context
      description: |
        Operating system version/distro, screenshots, JVM version, Kotlin version, gradle version,
        browser and version, etc.
