name: Feature request
description: Suggest an idea for this project
labels:
  - enhancement
  - triage
body:
  - type: textarea
    attributes:
      label: Feature description
    validations:
      required: true
  - type: textarea
    attributes:
      label: Use cases
      description: Describe why you need this feature, and how you intend on using it.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternatives and prior art
      description: Describe alternative solutions or features you've considered, and if relevant, prior art justifying or exemplifying all options and your choice.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
