name: Release

on:
  release:
    types: [ published ]

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  linux:
    name: Publish on Linux
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 23
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Run Tests & Generate Documentation
        run: ./gradlew allTests dokkaGenerate
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload Artifact to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/current'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      - name: Commit Documentation History
        #language=bash
        run: |
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ github.actor }}@users.noreply.github.com'
          git add --all docs/history
          git commit -m "Documentation history for release ${{ github.event.release.name }}"
          git push origin HEAD:${{ github.event.repository.default_branch }}]
